/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TrustlessMulticall__factory } from "./TrustlessMulticall__factory";
export { TrustlessMulticallViewOnly__factory } from "./TrustlessMulticallViewOnly__factory";
