/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { TrustlessMulticall__factory } from "./TrustlessMulticall__factory";
export { TrustlessMulticallRead__factory } from "./TrustlessMulticallRead__factory";
export { TrustlessMulticallViewOnly__factory } from "./TrustlessMulticallViewOnly__factory";
export { TrustlessMulticallWrite__factory } from "./TrustlessMulticallWrite__factory";
