/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TrustlessMulticallRead,
  TrustlessMulticallReadInterface,
} from "../TrustlessMulticallRead";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "callData",
            type: "bytes",
          },
        ],
        internalType: "struct TrustlessMulticallRead.ReadCall[]",
        name: "calls",
        type: "tuple[]",
      },
    ],
    name: "read",
    outputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "success",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "returnData",
            type: "bytes",
          },
        ],
        internalType: "struct TrustlessMulticallRead.ReadResult[]",
        name: "results",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TrustlessMulticallRead__factory {
  static readonly abi = _abi;
  static createInterface(): TrustlessMulticallReadInterface {
    return new utils.Interface(_abi) as TrustlessMulticallReadInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TrustlessMulticallRead {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TrustlessMulticallRead;
  }
}
