/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "SimpleViewContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleViewContract__factory>;
    getContractFactory(
      name: "TrustlessMulticall",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustlessMulticall__factory>;
    getContractFactory(
      name: "TrustlessMulticallRead",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustlessMulticallRead__factory>;
    getContractFactory(
      name: "TrustlessMulticallViewOnly",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustlessMulticallViewOnly__factory>;
    getContractFactory(
      name: "TrustlessMulticallWrite",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustlessMulticallWrite__factory>;

    getContractAt(
      name: "SimpleViewContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleViewContract>;
    getContractAt(
      name: "TrustlessMulticall",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustlessMulticall>;
    getContractAt(
      name: "TrustlessMulticallRead",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustlessMulticallRead>;
    getContractAt(
      name: "TrustlessMulticallViewOnly",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustlessMulticallViewOnly>;
    getContractAt(
      name: "TrustlessMulticallWrite",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustlessMulticallWrite>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
