/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TrustlessMulticall } from "./TrustlessMulticall";
export type { TrustlessMulticallViewOnly } from "./TrustlessMulticallViewOnly";
